<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DiscountCodeController;
use App\Http\Controllers\Admin\DomainTldPriceController;
use App\Http\Controllers\Admin\AudienceTypeController;
use App\Http\Controllers\Admin\AiSettingsController;
use App\Http\Controllers\Admin\FeatureModuleController;
use App\Http\Controllers\Admin\FinanceReportController;
use App\Http\Controllers\Admin\HelpTopicController;
use App\Http\Controllers\Admin\IrDomainRenewalController;
use App\Http\Controllers\Admin\LandingContactSubmissionController;
use App\Http\Controllers\Admin\LandingOrderController as AdminLandingOrderController;
use App\Http\Controllers\Admin\LandingSiteController;
use App\Http\Controllers\Admin\LandingFeatureController;
use App\Http\Controllers\Admin\LandingSiteSettingsController;
use App\Http\Controllers\Admin\LandingPageController;
use App\Http\Controllers\Admin\LandingSectionController;
use App\Http\Controllers\Admin\NutritionExerciseController;
use App\Http\Controllers\Admin\PaymentManagementController;
use App\Http\Controllers\Admin\RevenueAdjustmentController;
use App\Http\Controllers\Admin\SalesTeamController;
use App\Http\Controllers\Admin\SalesWithdrawalController;
use App\Http\Controllers\Admin\SupportAdjustmentController;
use App\Http\Controllers\Admin\SubscriptionPackageController;
use App\Http\Controllers\Admin\SupportTicketController;
use App\Http\Controllers\Admin\SmsSettingsController;
use App\Http\Controllers\Admin\SmsRevenueController;
use App\Http\Controllers\Admin\SmsOutboundManagementController;
use App\Http\Controllers\Admin\SmsCampaignApprovalController;
use App\Http\Controllers\Admin\SmsTemplateApprovalController;
use App\Http\Controllers\Admin\SpecializedCourseController;
use App\Http\Controllers\Admin\SpecializedCourseCategoryController;
use App\Http\Controllers\Admin\SpecializedCourseSettingsController;
use App\Http\Controllers\Admin\SpecializedCourseOrderController;
use App\Http\Controllers\Admin\SpecializedCourseReportController;
use App\Http\Controllers\Admin\SystemSettingsController;
use App\Http\Controllers\Admin\TenantManagementController;
use App\Http\Controllers\Admin\TelegramBotSettingsController;
use App\Http\Controllers\Admin\TeacherDashboardController;
use App\Http\Controllers\Admin\TeacherWithdrawalController;
use App\Http\Controllers\Admin\UserCreditController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\AdminAuthController;
use App\Http\Controllers\Auth\CentralOtpAuthApiController;
use App\Http\Controllers\Landing\LandingCustomerAuthController;
use App\Http\Controllers\Landing\LandingContactSubmissionController as PublicLandingContactSubmissionController;
use App\Http\Controllers\Landing\LandingOrderController;
use App\Http\Controllers\SupportTicketAttachmentController;
use Illuminate\Support\Facades\Route;

Route::post('/landing/contact-submissions', [PublicLandingContactSubmissionController::class, 'store'])
    ->name('landing.contact-submissions.store');

Route::prefix('/landing-api/v1')->group(function () {
    Route::prefix('/auth/otp')->group(function () {
        Route::post('/send', [LandingCustomerAuthController::class, 'send'])->name('landing.auth.otp.send');
        Route::post('/verify', [LandingCustomerAuthController::class, 'verify'])->name('landing.auth.otp.verify');
        Route::get('/me', [LandingCustomerAuthController::class, 'me'])->name('landing.auth.otp.me');
        Route::post('/profile', [LandingCustomerAuthController::class, 'updateProfile'])->name('landing.auth.otp.profile');
        Route::post('/logout', [LandingCustomerAuthController::class, 'logout'])->name('landing.auth.otp.logout');
    });

    Route::get('/checkout/preview', [LandingOrderController::class, 'preview'])->name('landing.checkout.preview');
    Route::post('/orders/checkout', [LandingOrderController::class, 'checkout'])->name('landing.orders.checkout');
    Route::get('/orders', [LandingOrderController::class, 'history'])->name('landing.orders.index');
    Route::get('/orders/{order}', [LandingOrderController::class, 'show'])->name('landing.orders.show');
    Route::get('/orders/{order}/domain-availability', [LandingOrderController::class, 'domainAvailability'])->name('landing.orders.domain-availability');
    Route::post('/orders/{order}/complete', [LandingOrderController::class, 'complete'])->name('landing.orders.complete');
    Route::get('/orders/payments/{payment}/callback', [LandingOrderController::class, 'callback'])->name('landing.orders.payments.callback');
});

foreach (config('tenancy.central_domains') as $domain) {
    Route::domain($domain)->group(function () {
        Route::get('/support-attachments/{attachment}', SupportTicketAttachmentController::class)->name('admin.support-attachments.show');

        Route::prefix('/api/v1/auth/otp')->group(function () {
            Route::post('/send', [CentralOtpAuthApiController::class, 'send'])->name('api.central.auth.otp.send');
            Route::post('/verify', [CentralOtpAuthApiController::class, 'verify'])->name('api.central.auth.otp.verify');
        });

        Route::get('/', function () {
            return auth()->check()
                ? redirect()->route('admin.dashboard')
                : redirect()->route('admin.login');
        });

        Route::middleware('guest')->group(function () {
            Route::get('/admin/login', [AdminAuthController::class, 'create'])->name('admin.login');
            Route::post('/admin/login', [AdminAuthController::class, 'store'])->name('admin.login.store');
        });

        Route::middleware('auth')->group(function () {
            Route::get('/admin', DashboardController::class)->name('admin.dashboard');
            Route::get('/admin/teacher-dashboard', TeacherDashboardController::class)->name('admin.teacher.dashboard');
            Route::get('/admin/teacher-withdrawals', TeacherWithdrawalController::class)->name('admin.teacher.withdrawals');
            Route::get('/admin/users', [UserController::class, 'index'])->name('admin.users.index');
            Route::get('/admin/users/create', [UserController::class, 'create'])->name('admin.users.create');
            Route::post('/admin/users', [UserController::class, 'store'])->name('admin.users.store');
            Route::get('/admin/users/{user}/edit', [UserController::class, 'edit'])->name('admin.users.edit');
            Route::put('/admin/users/{user}', [UserController::class, 'update'])->name('admin.users.update');
            Route::get('/admin/users/{user}/credit', [UserCreditController::class, 'edit'])->name('admin.users.credit.edit');
            Route::post('/admin/users/{user}/credit', [UserCreditController::class, 'store'])->name('admin.users.credit.store');
            Route::delete('/admin/users/{user}', [UserController::class, 'destroy'])->name('admin.users.destroy');
            Route::get('/admin/sales-team', [SalesTeamController::class, 'index'])->name('admin.sales-team.index');
            Route::get('/admin/sales-team/customers', [SalesTeamController::class, 'customers'])->name('admin.sales-team.customers');
            Route::post('/admin/sales-team/customers', [SalesTeamController::class, 'storeCustomer'])->name('admin.sales-team.customers.store');
            Route::get('/admin/sales-renewals', [SalesTeamController::class, 'renewals'])->name('admin.sales-team.renewals');
            Route::get('/admin/sales-team/{user}', [SalesTeamController::class, 'show'])->name('admin.sales-team.show');
            Route::get('/admin/sales-team/{user}/renewals', [SalesTeamController::class, 'userRenewals'])->name('admin.sales-team.user-renewals');
            Route::post('/admin/sales-team/{user}/follow-ups', [SalesTeamController::class, 'storeFollowUp'])->name('admin.sales-team.follow-ups.store');
            Route::get('/admin/sales-team/{user}/withdrawals', [SalesWithdrawalController::class, 'create'])->name('admin.sales-team.withdrawals.create');
            Route::post('/admin/sales-team/{user}/withdrawals/bank-accounts', [SalesWithdrawalController::class, 'storeBankAccount'])->name('admin.sales-team.withdrawals.bank-accounts.store');
            Route::put('/admin/sales-team/{user}/withdrawals/bank-accounts/{bankAccount}', [SalesWithdrawalController::class, 'updateBankAccount'])->name('admin.sales-team.withdrawals.bank-accounts.update');
            Route::delete('/admin/sales-team/{user}/withdrawals/bank-accounts/{bankAccount}', [SalesWithdrawalController::class, 'destroyBankAccount'])->name('admin.sales-team.withdrawals.bank-accounts.destroy');
            Route::post('/admin/sales-team/{user}/withdrawals', [SalesWithdrawalController::class, 'storeRequest'])->name('admin.sales-team.withdrawals.store');
            Route::get('/admin/sales-withdrawals', [SalesWithdrawalController::class, 'index'])->name('admin.sales-withdrawals.index');
            Route::put('/admin/sales-withdrawals/{withdrawal}', [SalesWithdrawalController::class, 'update'])->name('admin.sales-withdrawals.update');
            Route::get('/admin/tenants', [TenantManagementController::class, 'index'])->name('admin.tenants.index');
            Route::get('/admin/tenants/create', [TenantManagementController::class, 'create'])->name('admin.tenants.create');
            Route::post('/admin/tenants', [TenantManagementController::class, 'store'])->name('admin.tenants.store');
            Route::get('/admin/support-adjustments', [SupportAdjustmentController::class, 'index'])->name('admin.support-adjustments.index');
            Route::post('/admin/support-adjustments/{tenant}', [SupportAdjustmentController::class, 'store'])->name('admin.support-adjustments.store');
            Route::get('/admin/ir-domain-renewals', [IrDomainRenewalController::class, 'index'])->name('admin.ir-domain-renewals.index');
            Route::post('/admin/ir-domain-renewals/{tenant}', [IrDomainRenewalController::class, 'update'])->name('admin.ir-domain-renewals.update');
            Route::get('/admin/domain-tld-prices', [DomainTldPriceController::class, 'index'])->name('admin.domain-tld-prices.index');
            Route::post('/admin/domain-tld-prices/{domainTldPrice}', [DomainTldPriceController::class, 'update'])->name('admin.domain-tld-prices.update');
            Route::get('/admin/tenants/{tenant}/edit', [TenantManagementController::class, 'edit'])->name('admin.tenants.edit');
            Route::put('/admin/tenants/{tenant}', [TenantManagementController::class, 'update'])->name('admin.tenants.update');
            Route::post('/admin/tenants/{tenant}/renew', [TenantManagementController::class, 'renew'])->name('admin.tenants.renew');
            Route::post('/admin/tenants/{tenant}/impersonate', [TenantManagementController::class, 'impersonate'])->name('admin.tenants.impersonate');
            Route::post('/admin/tenants/{tenant}/panel-access', [TenantManagementController::class, 'updatePanelAccess'])->name('admin.tenants.panel-access.update');
            Route::post('/admin/tenants/{tenant}/sandbox-modes', [TenantManagementController::class, 'updateSandboxModes'])->name('admin.tenants.sandbox-modes.update');
            Route::post('/admin/tenants/{tenant}/feature-modules/{featureModule}/activate', [TenantManagementController::class, 'activateFeatureModule'])->name('admin.tenants.feature-modules.activate');
            Route::post('/admin/tenants/{tenant}/feature-modules/{tenantFeatureModule}/remove', [TenantManagementController::class, 'removeFeatureModule'])->name('admin.tenants.feature-modules.remove');
            Route::post('/admin/tenants/{tenant}/notifications', [TenantManagementController::class, 'sendNotification'])->name('admin.tenants.notifications.send');
            Route::post('/admin/tenants/{tenant}/nutrition-tokens/adjust', [TenantManagementController::class, 'adjustNutritionTokens'])->name('admin.tenants.nutrition-tokens.adjust');
            Route::get('/admin/tenants/{tenant}/delete', [TenantManagementController::class, 'confirmDestroy'])->name('admin.tenants.delete');
            Route::get('/admin/tenants/{tenant}', [TenantManagementController::class, 'show'])->name('admin.tenants.show');
            Route::delete('/admin/tenants/{tenant}', [TenantManagementController::class, 'destroy'])->name('admin.tenants.destroy');
            Route::get('/admin/landing-sites', [LandingSiteController::class, 'index'])->name('admin.landing-sites.index');
            Route::get('/admin/landing-sites/create', [LandingSiteController::class, 'create'])->name('admin.landing-sites.create');
            Route::post('/admin/landing-sites', [LandingSiteController::class, 'store'])->name('admin.landing-sites.store');
            Route::get('/admin/landing-sites/{landingSite}', [LandingSiteController::class, 'show'])->name('admin.landing-sites.show');
            Route::get('/admin/landing-sites/{landingSite}/edit', [LandingSiteController::class, 'edit'])->name('admin.landing-sites.edit');
            Route::put('/admin/landing-sites/{landingSite}', [LandingSiteController::class, 'update'])->name('admin.landing-sites.update');
            Route::get('/admin/landing-sites/{landingSite}/settings', [LandingSiteSettingsController::class, 'edit'])->name('admin.landing-sites.settings.edit');
            Route::post('/admin/landing-sites/{landingSite}/settings', [LandingSiteSettingsController::class, 'update'])->name('admin.landing-sites.settings.update');
            Route::delete('/admin/landing-sites/{landingSite}', [LandingSiteController::class, 'destroy'])->name('admin.landing-sites.destroy');
            Route::get('/admin/landing-sites/{landingSite}/features', [LandingFeatureController::class, 'index'])->name('admin.landing-sites.features.index');
            Route::get('/admin/landing-sites/{landingSite}/features/create', [LandingFeatureController::class, 'create'])->name('admin.landing-sites.features.create');
            Route::post('/admin/landing-sites/{landingSite}/features', [LandingFeatureController::class, 'store'])->name('admin.landing-sites.features.store');
            Route::get('/admin/landing-sites/{landingSite}/features/{feature}/edit', [LandingFeatureController::class, 'edit'])->name('admin.landing-sites.features.edit');
            Route::put('/admin/landing-sites/{landingSite}/features/{feature}', [LandingFeatureController::class, 'update'])->name('admin.landing-sites.features.update');
            Route::delete('/admin/landing-sites/{landingSite}/features/{feature}', [LandingFeatureController::class, 'destroy'])->name('admin.landing-sites.features.destroy');
            Route::get('/admin/landing-sites/{landingSite}/sections', [LandingSectionController::class, 'index'])->name('admin.landing-sites.sections.index');
            Route::put('/admin/landing-sites/{landingSite}/sections/order', [LandingSectionController::class, 'updateOrder'])->name('admin.landing-sites.sections.order');
            Route::get('/admin/landing-sites/{landingSite}/sections/{section}/edit', [LandingSectionController::class, 'edit'])->name('admin.landing-sites.sections.edit');
            Route::put('/admin/landing-sites/{landingSite}/sections/{section}', [LandingSectionController::class, 'update'])->name('admin.landing-sites.sections.update');
            Route::get('/admin/landing-sites/{landingSite}/pages', [LandingPageController::class, 'index'])->name('admin.landing-sites.pages.index');
            Route::get('/admin/landing-sites/{landingSite}/pages/{page}/edit', [LandingPageController::class, 'edit'])->name('admin.landing-sites.pages.edit');
            Route::put('/admin/landing-sites/{landingSite}/pages/{page}', [LandingPageController::class, 'update'])->name('admin.landing-sites.pages.update');
            Route::get('/admin/landing-sites/{landingSite}/contact-submissions', [LandingContactSubmissionController::class, 'index'])->name('admin.landing-sites.contact-submissions.index');
            Route::get('/admin/landing-orders', [AdminLandingOrderController::class, 'index'])->name('admin.landing-orders.index');
            Route::get('/admin/landing-orders/{order}', [AdminLandingOrderController::class, 'show'])->name('admin.landing-orders.show');
            Route::get('/admin/subscription-packages', [SubscriptionPackageController::class, 'index'])->name('admin.subscription-packages.index');
            Route::post('/admin/subscription-packages/matrix', [SubscriptionPackageController::class, 'updateMatrix'])->name('admin.subscription-packages.matrix.update');
            Route::get('/admin/subscription-packages/create', [SubscriptionPackageController::class, 'create'])->name('admin.subscription-packages.create');
            Route::post('/admin/subscription-packages', [SubscriptionPackageController::class, 'store'])->name('admin.subscription-packages.store');
            Route::get('/admin/subscription-packages/{subscriptionPackage}/edit', [SubscriptionPackageController::class, 'edit'])->name('admin.subscription-packages.edit');
            Route::put('/admin/subscription-packages/{subscriptionPackage}', [SubscriptionPackageController::class, 'update'])->name('admin.subscription-packages.update');
            Route::delete('/admin/subscription-packages/{subscriptionPackage}', [SubscriptionPackageController::class, 'destroy'])->name('admin.subscription-packages.destroy');
            Route::get('/admin/feature-modules', [FeatureModuleController::class, 'index'])->name('admin.feature-modules.index');
            Route::get('/admin/feature-modules/create', [FeatureModuleController::class, 'create'])->name('admin.feature-modules.create');
            Route::post('/admin/feature-modules', [FeatureModuleController::class, 'store'])->name('admin.feature-modules.store');
            Route::get('/admin/feature-modules/{featureModule}/edit', [FeatureModuleController::class, 'edit'])->name('admin.feature-modules.edit');
            Route::put('/admin/feature-modules/{featureModule}', [FeatureModuleController::class, 'update'])->name('admin.feature-modules.update');
            Route::delete('/admin/feature-modules/{featureModule}', [FeatureModuleController::class, 'destroy'])->name('admin.feature-modules.destroy');
            Route::get('/admin/help-topics', [HelpTopicController::class, 'index'])->name('admin.help-topics.index');
            Route::get('/admin/help-topics/create', [HelpTopicController::class, 'create'])->name('admin.help-topics.create');
            Route::post('/admin/help-topics', [HelpTopicController::class, 'store'])->name('admin.help-topics.store');
            Route::get('/admin/help-topics/{helpTopic}/edit', [HelpTopicController::class, 'edit'])->name('admin.help-topics.edit');
            Route::put('/admin/help-topics/{helpTopic}', [HelpTopicController::class, 'update'])->name('admin.help-topics.update');
            Route::delete('/admin/help-topics/{helpTopic}', [HelpTopicController::class, 'destroy'])->name('admin.help-topics.destroy');
            Route::get('/admin/nutrition-exercises', [NutritionExerciseController::class, 'index'])->name('admin.nutrition-exercises.index');
            Route::get('/admin/nutrition-exercises/groups/create', [NutritionExerciseController::class, 'createGroup'])->name('admin.nutrition-exercises.groups.create');
            Route::post('/admin/nutrition-exercises/groups', [NutritionExerciseController::class, 'storeGroup'])->name('admin.nutrition-exercises.groups.store');
            Route::get('/admin/nutrition-exercises/groups/{group}/edit', [NutritionExerciseController::class, 'editGroup'])->name('admin.nutrition-exercises.groups.edit');
            Route::put('/admin/nutrition-exercises/groups/{group}', [NutritionExerciseController::class, 'updateGroup'])->name('admin.nutrition-exercises.groups.update');
            Route::delete('/admin/nutrition-exercises/groups/{group}', [NutritionExerciseController::class, 'destroyGroup'])->name('admin.nutrition-exercises.groups.destroy');
            Route::get('/admin/nutrition-exercises/items/create', [NutritionExerciseController::class, 'createExercise'])->name('admin.nutrition-exercises.items.create');
            Route::post('/admin/nutrition-exercises/items', [NutritionExerciseController::class, 'storeExercise'])->name('admin.nutrition-exercises.items.store');
            Route::get('/admin/nutrition-exercises/items/{exercise}/edit', [NutritionExerciseController::class, 'editExercise'])->name('admin.nutrition-exercises.items.edit');
            Route::put('/admin/nutrition-exercises/items/{exercise}', [NutritionExerciseController::class, 'updateExercise'])->name('admin.nutrition-exercises.items.update');
            Route::delete('/admin/nutrition-exercises/items/{exercise}', [NutritionExerciseController::class, 'destroyExercise'])->name('admin.nutrition-exercises.items.destroy');
            Route::get('/admin/specialized-courses', [SpecializedCourseController::class, 'index'])->name('admin.specialized-courses.index');
            Route::get('/admin/specialized-courses/create', [SpecializedCourseController::class, 'create'])->name('admin.specialized-courses.create');
            Route::post('/admin/specialized-courses', [SpecializedCourseController::class, 'store'])->name('admin.specialized-courses.store');
            Route::get('/admin/specialized-courses/{specializedCourse}/edit', [SpecializedCourseController::class, 'edit'])->name('admin.specialized-courses.edit');
            Route::put('/admin/specialized-courses/{specializedCourse}', [SpecializedCourseController::class, 'update'])->name('admin.specialized-courses.update');
            Route::delete('/admin/specialized-courses/{specializedCourse}', [SpecializedCourseController::class, 'destroy'])->name('admin.specialized-courses.destroy');
            Route::get('/admin/specialized-course-settings', [SpecializedCourseSettingsController::class, 'index'])->name('admin.specialized-course-settings.index');
            Route::get('/admin/specialized-course-settings/{audienceType}/edit', [SpecializedCourseSettingsController::class, 'edit'])->name('admin.specialized-course-settings.edit');
            Route::put('/admin/specialized-course-settings/{audienceType}', [SpecializedCourseSettingsController::class, 'update'])->name('admin.specialized-course-settings.update');
            Route::get('/admin/specialized-course-categories', [SpecializedCourseCategoryController::class, 'index'])->name('admin.specialized-course-categories.index');
            Route::get('/admin/specialized-course-categories/create', [SpecializedCourseCategoryController::class, 'create'])->name('admin.specialized-course-categories.create');
            Route::post('/admin/specialized-course-categories', [SpecializedCourseCategoryController::class, 'store'])->name('admin.specialized-course-categories.store');
            Route::get('/admin/specialized-course-categories/{specializedCourseCategory}/edit', [SpecializedCourseCategoryController::class, 'edit'])->name('admin.specialized-course-categories.edit');
            Route::put('/admin/specialized-course-categories/{specializedCourseCategory}', [SpecializedCourseCategoryController::class, 'update'])->name('admin.specialized-course-categories.update');
            Route::delete('/admin/specialized-course-categories/{specializedCourseCategory}', [SpecializedCourseCategoryController::class, 'destroy'])->name('admin.specialized-course-categories.destroy');
            Route::get('/admin/specialized-course-orders', [SpecializedCourseOrderController::class, 'index'])->name('admin.specialized-course-orders.index');
            Route::get('/admin/specialized-course-orders/tenant-users', [SpecializedCourseOrderController::class, 'tenantUsers'])->name('admin.specialized-course-orders.tenant-users');
            Route::post('/admin/specialized-course-orders/manual-grants', [SpecializedCourseOrderController::class, 'storeManual'])->name('admin.specialized-course-orders.manual-grants.store');
            Route::get('/admin/specialized-course-reports', [SpecializedCourseReportController::class, 'index'])->name('admin.specialized-course-reports.index');
            Route::get('/admin/discount-codes', [DiscountCodeController::class, 'index'])->name('admin.discount-codes.index');
            Route::get('/admin/discount-codes/create', [DiscountCodeController::class, 'create'])->name('admin.discount-codes.create');
            Route::post('/admin/discount-codes', [DiscountCodeController::class, 'store'])->name('admin.discount-codes.store');
            Route::get('/admin/discount-codes/{discountCode}/edit', [DiscountCodeController::class, 'edit'])->name('admin.discount-codes.edit');
            Route::put('/admin/discount-codes/{discountCode}', [DiscountCodeController::class, 'update'])->name('admin.discount-codes.update');
            Route::delete('/admin/discount-codes/{discountCode}', [DiscountCodeController::class, 'destroy'])->name('admin.discount-codes.destroy');
            Route::get('/admin/audience-types', [AudienceTypeController::class, 'index'])->name('admin.audience-types.index');
            Route::get('/admin/audience-types/create', [AudienceTypeController::class, 'create'])->name('admin.audience-types.create');
            Route::post('/admin/audience-types', [AudienceTypeController::class, 'store'])->name('admin.audience-types.store');
            Route::get('/admin/audience-types/{audienceType}/edit', [AudienceTypeController::class, 'edit'])->name('admin.audience-types.edit');
            Route::put('/admin/audience-types/{audienceType}', [AudienceTypeController::class, 'update'])->name('admin.audience-types.update');
            Route::delete('/admin/audience-types/{audienceType}', [AudienceTypeController::class, 'destroy'])->name('admin.audience-types.destroy');
            Route::get('/admin/system-settings', [SystemSettingsController::class, 'edit'])->name('admin.system-settings.edit');
            Route::put('/admin/system-settings', [SystemSettingsController::class, 'update'])->name('admin.system-settings.update');
            Route::get('/admin/ai-settings', [AiSettingsController::class, 'edit'])->name('admin.ai-settings.edit');
            Route::put('/admin/ai-settings', [AiSettingsController::class, 'update'])->name('admin.ai-settings.update');
            Route::get('/admin/finance', [FinanceReportController::class, 'index'])->name('admin.finance.index');
            Route::get('/admin/sms-settings', [SmsSettingsController::class, 'edit'])->name('admin.sms-settings.edit');
            Route::put('/admin/sms-settings', [SmsSettingsController::class, 'update'])->name('admin.sms-settings.update');
            Route::get('/admin/telegram-bot-settings', [TelegramBotSettingsController::class, 'edit'])->name('admin.telegram-bot-settings.edit');
            Route::put('/admin/telegram-bot-settings', [TelegramBotSettingsController::class, 'update'])->name('admin.telegram-bot-settings.update');
            Route::get('/admin/sms-revenue', [SmsRevenueController::class, 'index'])->name('admin.sms-revenue.index');
            Route::post('/admin/sms-revenue/withdrawals', [SmsRevenueController::class, 'store'])->name('admin.sms-revenue.store');
            Route::get('/admin/sms-outbounds', [SmsOutboundManagementController::class, 'index'])->name('admin.sms-outbounds.index');
            Route::get('/admin/sms-templates', [SmsTemplateApprovalController::class, 'index'])->name('admin.sms-templates.index');
            Route::put('/admin/sms-templates/{tenant}/{templateKey}', [SmsTemplateApprovalController::class, 'update'])->name('admin.sms-templates.update');
            Route::get('/admin/sms-campaigns', [SmsCampaignApprovalController::class, 'index'])->name('admin.sms-campaigns.index');
            Route::put('/admin/sms-campaigns/{tenant}/{campaignId}', [SmsCampaignApprovalController::class, 'update'])->name('admin.sms-campaigns.update');
            Route::get('/admin/payments', [PaymentManagementController::class, 'index'])->name('admin.payments.index');
            Route::get('/admin/revenue-adjustments', [RevenueAdjustmentController::class, 'index'])->name('admin.revenue-adjustments.index');
            Route::post('/admin/revenue-adjustments/tenant/{payment}', [RevenueAdjustmentController::class, 'storeTenant'])->name('admin.revenue-adjustments.tenant.store');
            Route::post('/admin/revenue-adjustments/landing/{payment}', [RevenueAdjustmentController::class, 'storeLanding'])->name('admin.revenue-adjustments.landing.store');
            Route::get('/admin/support-tickets', [SupportTicketController::class, 'index'])->name('admin.support-tickets.index');
            Route::get('/admin/support-tickets/{ticket}', [SupportTicketController::class, 'show'])->name('admin.support-tickets.show');
            Route::post('/admin/support-tickets/{ticket}/reply', [SupportTicketController::class, 'reply'])->name('admin.support-tickets.reply');
            Route::post('/admin/support-tickets/{ticket}/close', [SupportTicketController::class, 'close'])->name('admin.support-tickets.close');

            Route::post('/admin/logout', [AdminAuthController::class, 'destroy'])->name('admin.logout');
        });
    });
}
