<?php

declare(strict_types=1);

return [
    'default_locale' => env('TENANT_DEFAULT_LOCALE', 'fa'),
    'fallback_locale' => env('TENANT_FALLBACK_LOCALE', 'fa'),
    'default_country' => env('TENANT_DEFAULT_COUNTRY', 'IR'),

    'supported' => [
        'fa' => [
            'label' => 'فارسی',
            'native_label' => 'فارسی',
            'dir' => 'rtl',
            'html_lang' => 'fa',
            'og_locale' => 'fa_IR',
            'date_locale' => 'fa-IR',
            'calendar' => 'jalali',
            'numbering_system' => 'arabext',
            'currency' => 'IRR',
            'enabled' => true,
            'selectable' => true,
        ],
        'en' => [
            'label' => 'English',
            'native_label' => 'English',
            'dir' => 'ltr',
            'html_lang' => 'en',
            'og_locale' => 'en_US',
            'date_locale' => 'en-US',
            'calendar' => 'gregorian',
            'numbering_system' => 'latn',
            'currency' => 'USD',
            'enabled' => true,
            'selectable' => true,
        ],
        'ar' => [
            'label' => 'Arabic',
            'native_label' => 'العربية',
            'dir' => 'rtl',
            'html_lang' => 'ar',
            'og_locale' => 'ar_SA',
            'date_locale' => 'ar-SA',
            'calendar' => 'hijri',
            'numbering_system' => 'arab',
            'currency' => 'SAR',
            'enabled' => true,
            'selectable' => true,
        ],
        'de' => [
            'label' => 'German',
            'native_label' => 'Deutsch',
            'dir' => 'ltr',
            'html_lang' => 'de',
            'og_locale' => 'de_DE',
            'date_locale' => 'de-DE',
            'calendar' => 'gregorian',
            'numbering_system' => 'latn',
            'currency' => 'EUR',
            'enabled' => true,
            'selectable' => true,
        ],
    ],

    'countries' => [
        'IR' => [
            'label' => 'ایران',
            'native_label' => 'ایران',
            'currency' => 'IRR',
            'timezone' => 'Asia/Tehran',
            'enabled' => true,
            'selectable' => true,
        ],
        'US' => [
            'label' => 'United States',
            'native_label' => 'United States',
            'currency' => 'USD',
            'timezone' => 'America/New_York',
            'enabled' => true,
            'selectable' => true,
        ],
        'SA' => [
            'label' => 'Saudi Arabia',
            'native_label' => 'السعودية',
            'currency' => 'SAR',
            'timezone' => 'Asia/Riyadh',
            'enabled' => true,
            'selectable' => true,
        ],
        'DE' => [
            'label' => 'Germany',
            'native_label' => 'Deutschland',
            'currency' => 'EUR',
            'timezone' => 'Europe/Berlin',
            'enabled' => true,
            'selectable' => true,
        ],
    ],
];
