import { useEffect, useMemo, useState } from "react";
import { ChevronLeft, Clock3, MapPin, Phone, X } from "lucide-react";
import { api } from "@/lib/api";

type Resume = { templateType: "personal" | "beauty_salon"; sections: Record<string, boolean>; content: Record<string, unknown>; businessStatus?: { available: boolean; isOpen: boolean; label: string; opensAt: string | null; closesAt: string | null } };
const lines = (value: unknown) => String(value ?? "").split("\n").map((line) => line.trim()).filter(Boolean);
const parts = (value: string) => value.split("|").map((item) => item.trim());
type GalleryItem = { url: string; title: string };
const galleryItems = (value: unknown): GalleryItem[] => lines(value).map((line, index) => { const [url, title] = parts(line); return { url, title: title || `نمونه‌کار ${index + 1}` }; }).filter((item) => item.url !== "");

export default function BusinessResumePublicPage() {
  const [resume, setResume] = useState<Resume | null>(null);
  const [failed, setFailed] = useState(false);
  useEffect(() => {
    const preview = new URLSearchParams(window.location.search).get("preview") === "1";
    (preview ? api.businessResume.get() : api.businessResume.publicGet()).then((result) => {
      if (result.success && result.data.templateType) setResume(result.data as Resume); else setFailed(true);
    });
  }, []);
  if (failed) return <div className="grid min-h-screen place-items-center bg-[#08080e] px-5 text-center font-bold text-[#ededf2]">این رزومه هنوز منتشر نشده است.</div>;
  if (!resume) return <div className="grid min-h-screen place-items-center bg-[#08080e] font-medium text-[#ededf2]">در حال بارگذاری...</div>;
  return resume.templateType === "personal" ? <PersonalResume resume={resume} /> : <BeautyResume resume={resume} />;
}

function PersonalResume({ resume }: { resume: Resume }) {
  const content = resume.content as Record<string, string>;
  const visible = (key: string) => !!resume.sections[key];
  const gallery = useMemo(() => galleryItems(content.gallery), [content.gallery]);
  const stats = lines(content.stats).slice(0, 3);
  const reviews = lines(content.reviews);
  return <main dir="rtl" className="min-h-screen bg-[#08080e] font-[Vazirmatn,sans-serif] text-[#f2f2f7]"><div className="mx-auto min-h-screen max-w-[430px] pb-24">
    {visible("hero") ? <section className="relative h-[340px] overflow-hidden bg-[#1b1b22]"><img src={content.heroImage || "https://images.unsplash.com/photo-1702865272115-5afdbae975af?w=1200&q=80&auto=format&fit=crop"} alt="فضای سالن" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(8,8,14,.15),rgba(8,8,14,.75)_55%,#08080e)]" /><div className="absolute inset-x-[18px] bottom-4"><BusinessStatus status={resume.businessStatus} variant="personal" /><h1 className="mt-2.5 text-[26px] font-extrabold leading-[1.3] text-white">{content.title || "رزومه شخصی"}</h1><p className="mt-1 text-[13px] text-[#b9b9c8]">{content.subtitle}</p></div></section> : null}
    <div className="space-y-[22px] px-4 pb-6 pt-1">
      {visible("stats") && stats.length ? <section className="grid grid-cols-3 gap-2.5">{stats.map((line) => { const [value, label] = parts(line); return <div key={line} className="rounded-[14px] border border-[#232336] bg-[#14141f] px-2 py-3.5 text-center"><div className="text-xl font-extrabold text-[#ededf2]">{value}</div><div className="mt-1 text-[11px] text-[#8a8a9c]">{label}</div></div>; })}</section> : null}
      {visible("about") ? <Section title="درباره من"><div className="flex items-start gap-3.5"><img src={content.profileImage || "https://images.unsplash.com/photo-1618049049816-43a00d5b0c3d?w=500&q=80&auto=format&fit=crop"} alt="پرتره" className="h-24 w-24 shrink-0 rounded-full object-cover" /><p className="m-0 text-[13.5px] leading-[2] text-[#b9b9c8]">{content.about}</p></div></Section> : null}
      {visible("specialties") ? <Section title="تخصص‌ها"><div className="flex flex-wrap gap-2">{lines(content.specialties).map((item) => <span key={item} className="rounded-full border border-[#262842] bg-[#14141f] px-[13px] py-2 text-[12.5px] text-[#d0d0dc]">{item}</span>)}</div></Section> : null}
      {visible("timeline") ? <Section title="سوابق و مدارک"><div>{lines(content.timeline).map((line, index, all) => { const [title, period, description] = parts(line); return <div key={line} className="flex gap-3"><div className="flex w-3 shrink-0 flex-col items-center"><i className={index === 0 ? "mt-1.5 h-2.5 w-2.5 rounded-full bg-[#ededf2]" : "mt-1.5 h-2.5 w-2.5 rounded-full bg-[#3a3a52]"} />{index < all.length - 1 ? <i className="w-px flex-1 bg-[#262842]" /> : null}</div><div className={index < all.length - 1 ? "pb-[18px]" : ""}><div className="text-sm font-bold text-[#f2f2f7]">{title}</div><div className="mt-1 text-xs text-[#8a8a9c]">{period}</div>{description ? <div className="mt-1 text-xs text-[#a3a3b4]">{description}</div> : null}</div></div>; })}</div></Section> : null}
      {visible("gallery") && gallery.length ? <Section title="نمونه کارها"><Gallery items={gallery} variant="personal" /></Section> : null}
      {visible("services") ? <Section title="خدمات و تعرفه"><div className="space-y-2">{lines(content.services).map((line) => { const [name, duration, price, description] = parts(line); return <div key={line} className="flex items-start justify-between gap-3 rounded-[14px] border border-[#232336] bg-[#14141f] px-[15px] py-[13px]"><div className="min-w-0"><div className="text-sm font-semibold text-[#f2f2f7]">{name}</div>{description ? <p className="mt-1 text-[11.5px] leading-[1.7] text-[#8a8a9c]">{description}</p> : null}<div className="mt-1 text-[11px] text-[#6f6f80]">{duration}</div></div><div className="shrink-0 pt-0.5 text-[13.5px] font-bold text-[#ededf2]">{price}</div></div>; })}</div></Section> : null}
      {visible("reviews") && reviews.length ? <Section title="نظر مشتریان" trailing="★ ۴٫۹ از ۲۱۴ نظر"><div className="-mx-4 flex snap-x gap-2.5 overflow-x-auto px-4 pb-1.5">{reviews.map((line) => { const [name, rating, text] = parts(line); return <article key={line} className="w-[86%] shrink-0 snap-end rounded-2xl border border-[#232336] bg-[#14141f] px-[15px] py-[14px]"><div className="flex items-center justify-between gap-2"><b className="text-[13px]">{name}</b><span className="text-xs text-[#ededf2]">{rating}</span></div><p className="mt-2.5 text-[12.5px] leading-[1.9] text-[#a3a3b4]">{text}</p></article>; })}</div><div className="mt-1 flex items-center justify-center gap-1.5 text-[11px] text-[#5a5a6c]"><ChevronLeft className="h-3 w-3" />برای دیدن نظرهای بیشتر، بکشید</div></Section> : null}
      {visible("contact") ? <Section title="آدرس و تماس"><div className="space-y-[13px] rounded-2xl border border-[#232336] bg-[#14141f] p-[15px]">{lines(content.contact).map((line, index) => <div key={line} className="flex items-start gap-2.5 text-[13px] leading-[1.8] text-[#c8c8d6]">{index === 0 ? <MapPin className="mt-0.5 h-[17px] w-[17px] shrink-0 text-[#ededf2]" /> : index === 1 ? <Phone className="h-[17px] w-[17px] shrink-0 text-[#ededf2]" /> : <Clock3 className="h-[17px] w-[17px] shrink-0 text-[#ededf2]" />}<span className={index === 1 ? "direction-ltr" : ""}>{line}</span></div>)}{content.mapImage ? <img src={content.mapImage} alt="نقشه موقعیت" className="h-[140px] w-full rounded-xl object-cover" /> : null}</div></Section> : null}
    </div>
  </div><StickyBooking label={content.ctaLabel || "رزرو نوبت آنلاین"} personal /></main>;
}

function BeautyResume({ resume }: { resume: Resume }) {
  const content = resume.content as Record<string, string>; const visible = (key: string) => !!resume.sections[key]; const gallery = galleryItems(content.gallery);
  return <main dir="rtl" className="min-h-screen bg-[#0b070d] font-[Vazirmatn,sans-serif] text-[#f5eef0]"><div className="mx-auto max-w-[430px] pb-24">
    {visible("hero") ? <section className="relative h-[350px] overflow-hidden bg-[#301723]"><img src={content.heroImage || "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1200&q=80&auto=format&fit=crop"} className="h-full w-full object-cover opacity-85" /><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(11,7,13,.1),rgba(11,7,13,.72)_55%,#0b070d)]" /><div className="absolute inset-x-[18px] bottom-4"><BusinessStatus status={resume.businessStatus} variant="beauty" /><h1 className="mt-2.5 text-[26px] font-extrabold">{content.title || "سالن زیبایی"}</h1><p className="mt-1 text-[13px] text-[#c3b6bd]">{content.subtitle}</p></div></section> : null}
    <div className="space-y-[22px] px-4 pb-6 pt-1">
      {visible("manager") ? <section className="flex items-center gap-3 rounded-2xl border border-[#2a1f2e] bg-[#150f18] p-[14px]"><img src={content.profileImage || "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=500&q=80&auto=format&fit=crop"} className="h-24 w-24 shrink-0 rounded-full object-cover" /><div><b className="text-base">{content.manager?.split("|")[0] || "مدیر سالن"}</b><p className="mt-1 text-xs leading-[1.8] text-[#b39aa4]">{content.manager?.split("|")[1] || content.manager}</p><span className="mt-1.5 block text-xs text-[#ff6f9c]">★★★★★ <i className="not-italic text-[#8b7a83]">۴٫۹ از ۲۴۸ نظر</i></span></div></section> : null}
      {visible("stats") ? <section className="grid grid-cols-3 gap-2">{lines(content.stats).slice(0, 3).map((line) => { const [value, label] = parts(line); return <div key={line} className="rounded-[14px] border border-[#2a1f2e] bg-[#150f18] px-2 py-[13px] text-center"><div className="text-[19px] font-extrabold text-[#ff6f9c]">{value}</div><div className="mt-1 text-[10.5px] text-[#8b7a83]">{label}</div></div>; })}</section> : null}
      {visible("about") ? <PinkSection title="درباره سالن"><p className="text-[12.5px] leading-[2.1] text-[#a89099]">{content.about}</p></PinkSection> : null}
      {visible("categories") ? <PinkSection title="دسته‌بندی خدمات"><div className="flex gap-2 overflow-x-auto pb-1">{lines(content.categories).map((item, index) => <span key={item} className={index === 0 ? "shrink-0 rounded-full bg-[#ff6f9c] px-3.5 py-2 text-[12.5px] font-semibold text-[#2a0c16]" : "shrink-0 rounded-full border border-[#2f2334] bg-[#150f18] px-3.5 py-2 text-[12.5px] text-[#b39aa4]"}>{item}</span>)}</div></PinkSection> : null}
      {visible("services") ? <PinkSection title="خدمات و تعرفه"><div className="space-y-2">{lines(content.services).map((line) => { const [name, duration, price, description] = parts(line); return <div key={line} className="flex justify-between gap-3 rounded-[14px] border border-[#2a1f2e] bg-[#150f18] p-[13px_15px]"><div><b className="text-sm">{name}</b><p className="mt-1 text-[11.5px] leading-[1.75] text-[#9c848d]">{description}</p><span className="text-[11px] text-[#6f5f68]">{duration}</span></div><b className="shrink-0 text-[13px] text-[#ff6f9c]">{price}</b></div>; })}</div></PinkSection> : null}
      {visible("team") ? <PinkSection title="تیم متخصصان"><div className="flex gap-2.5 overflow-x-auto">{lines(content.team).map((line) => { const [name, specialty, image] = parts(line); return <div key={line} className="w-[118px] shrink-0 rounded-[14px] border border-[#2a1f2e] bg-[#150f18] p-3 text-center"><img src={image || content.profileImage} className="mx-auto h-[62px] w-[62px] rounded-full object-cover" /><b className="mt-2 block text-[12.5px]">{name}</b><span className="text-[10.5px] text-[#8b7a83]">{specialty}</span></div>; })}</div></PinkSection> : null}
      {visible("gallery") && gallery.length ? <PinkSection title="نمونه کارها"><Gallery items={gallery} variant="beauty" /></PinkSection> : null}
      {visible("reviews") ? <PinkSection title="نظر مشتریان"><div className="-mx-4 flex gap-2.5 overflow-x-auto px-4">{lines(content.reviews).map((line) => { const [name, rating, text] = parts(line); return <article key={line} className="w-[86%] shrink-0 rounded-2xl border border-[#2a1f2e] bg-[#150f18] p-[14px_15px]"><div className="flex justify-between"><b className="text-[13px]">{name}</b><span className="text-xs text-[#ff6f9c]">{rating}</span></div><p className="mt-2.5 text-[12.5px] leading-[1.9] text-[#a89099]">{text}</p></article>; })}</div></PinkSection> : null}
      {visible("contact") ? <PinkSection title="آدرس و تماس"><div className="space-y-2.5">{content.mapImage ? <img src={content.mapImage} className="h-[140px] w-full rounded-xl object-cover" /> : null}<p className="text-[12.5px] leading-[2] text-[#a89099]">{lines(content.contact)[0]}</p><div className="flex gap-2"><a href={`tel:${lines(content.contact)[1] || ""}`} className="flex h-11 flex-1 items-center justify-center rounded-xl border border-[#33253a] bg-[#150f18] text-[13px] font-semibold">تماس</a><a href="#" className="flex h-11 flex-1 items-center justify-center rounded-xl border border-[#33253a] bg-[#150f18] text-[13px] font-semibold">مسیریابی</a></div></div></PinkSection> : null}
    </div></div><div className="fixed inset-x-0 bottom-0 mx-auto max-w-[430px] bg-[linear-gradient(180deg,transparent,#0b070d_45%)] px-4 pb-[18px] pt-[14px]"><button onClick={() => window.location.assign("/booking")} className="h-[52px] w-full rounded-[14px] bg-[#ff6f9c] text-[15px] font-extrabold text-[#2a0c16]">{content.ctaLabel || "رزرو نوبت آنلاین"}</button></div></main>;
}
function PinkSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="mb-3 text-[15px] font-bold">{title}</h2>{children}</section>; }
function Section({ title, trailing, children }: { title: string; trailing?: string; children: React.ReactNode }) { return <section><div className="mb-3 flex items-center gap-2.5"><h2 className="shrink-0 text-base font-bold text-[#f2f2f7]">{title}</h2><i className="h-px flex-1 bg-[#232336]" />{trailing ? <span className="shrink-0 text-[12.5px] font-semibold text-[#ededf2]">{trailing}</span> : null}</div>{children}</section>; }
function Gallery({ items, variant }: { items: GalleryItem[]; variant: "personal" | "beauty" }) { const [selected, setSelected] = useState<GalleryItem | null>(null); const dark = variant === "personal"; return <><div className="grid grid-cols-3 gap-2">{items.map((item, index) => <button key={`${item.url}-${index}`} type="button" onClick={() => setSelected(item)} className="group relative aspect-square overflow-hidden rounded-xl bg-[#14141f] text-start"><img src={item.url} alt={item.title} className="h-full w-full object-cover transition duration-200 group-hover:scale-105" /><span className="absolute inset-x-0 bottom-0 bg-black/60 px-1.5 py-1 text-center text-[10px] font-medium leading-4 text-white">{item.title}</span></button>)}</div>{selected ? <div role="dialog" aria-modal="true" aria-label={selected.title} className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4" onClick={() => setSelected(null)}><div className={`relative w-full max-w-[720px] overflow-hidden rounded-2xl border ${dark ? "border-[#36364b] bg-[#14141f]" : "border-[#553342] bg-[#150f18]"}`} onClick={(event) => event.stopPropagation()}><button type="button" aria-label="بستن" onClick={() => setSelected(null)} className="absolute end-3 top-3 z-10 grid h-9 w-9 place-items-center rounded-full bg-black/60 text-white"><X className="h-5 w-5" /></button><img src={selected.url} alt={selected.title} className="max-h-[75vh] w-full object-contain" /><div className="px-4 py-3 text-center text-sm font-bold text-white">{selected.title}</div></div></div> : null}</>; }
function BusinessStatus({ status, variant }: { status?: Resume["businessStatus"]; variant: "personal" | "beauty" }) { if (!status) return null; const beauty = variant === "beauty"; return <span className={`inline-flex items-center gap-2 rounded-full px-2.5 py-1 text-[11px] font-semibold ${beauty ? "border border-[#ff6f9c]/35 bg-[#ff6f9c]/15 text-[#ffa6c3]" : "border border-white/35 bg-white/15 text-[#d6d6e0]"}`}><i className={`h-1.5 w-1.5 rounded-full ${status.isOpen ? "bg-[#4ade80]" : "bg-[#fb7185]"}`} />{status.label}</span>; }
function StickyBooking({ label, personal }: { label: string; personal?: boolean }) { return <div className="fixed inset-x-0 bottom-0 z-10 mx-auto flex max-w-[430px] gap-2.5 px-4 pb-[calc(16px+env(safe-area-inset-bottom))] pt-[18px]" style={{ background: "linear-gradient(180deg, rgba(8,8,14,0) 0%, #0c0c14 30%)" }}><button type="button" onClick={() => window.location.assign("/booking")} className="flex h-[52px] flex-1 items-center justify-center gap-2 rounded-[14px] text-[15px] font-extrabold" style={{ backgroundColor: "#fbbf24", color: "#231500" }}>{label}<ChevronLeft className="h-[17px] w-[17px]" /></button>{personal ? <a href="tel:" className="grid h-[52px] w-[52px] place-items-center rounded-[14px] border border-[#262842] bg-[#14141f] text-[#d0d0dc]"><Phone className="h-5 w-5" /></a> : null}</div>; }
