<?php

declare(strict_types=1);

namespace App\Domain\Tenant\Models;

use Illuminate\Database\Eloquent\Model;

class CustomerClubSetting extends Model
{
    protected $fillable = [
        'is_enabled',
        'points_enabled',
        'wallet_enabled',
        'tiers_enabled',
        'rewards_enabled',
        'auto_tier_upgrade_enabled',
        'appointment_points_enabled',
        'appointment_fixed_points',
        'appointment_points_per_100k',
        'appointment_wallet_enabled',
        'appointment_fixed_wallet',
        'store_points_enabled',
        'store_fixed_points',
        'store_points_per_100k',
        'store_wallet_enabled',
        'store_wallet_percent',
        'welcome_bonus_enabled',
        'welcome_bonus_points',
        'welcome_bonus_wallet',
        'birthday_bonus_enabled',
        'birthday_bonus_points',
        'birthday_bonus_wallet',
        'manual_adjustments_enabled',
        'allow_negative_wallet',
        'show_wallet_to_customer',
        'show_points_to_customer',
        'show_tier_to_customer',
        'nutrition_rewards_enabled',
        'nutrition_daily_food_log_enabled',
        'nutrition_daily_food_log_points',
        'nutrition_per_meal_log_enabled',
        'nutrition_per_meal_log_points',
        'nutrition_daily_water_log_enabled',
        'nutrition_daily_water_log_points',
        'nutrition_weight_loss_reward_enabled',
        'nutrition_weight_loss_reward_points',
        'nutrition_online_diet_request_reward_enabled',
        'nutrition_online_diet_request_reward_points',
        'metadata',
    ];

    protected $casts = [
        'is_enabled' => 'boolean',
        'points_enabled' => 'boolean',
        'wallet_enabled' => 'boolean',
        'tiers_enabled' => 'boolean',
        'rewards_enabled' => 'boolean',
        'auto_tier_upgrade_enabled' => 'boolean',
        'appointment_points_enabled' => 'boolean',
        'appointment_fixed_points' => 'integer',
        'appointment_points_per_100k' => 'integer',
        'appointment_wallet_enabled' => 'boolean',
        'appointment_fixed_wallet' => 'integer',
        'store_points_enabled' => 'boolean',
        'store_fixed_points' => 'integer',
        'store_points_per_100k' => 'integer',
        'store_wallet_enabled' => 'boolean',
        'store_wallet_percent' => 'integer',
        'welcome_bonus_enabled' => 'boolean',
        'welcome_bonus_points' => 'integer',
        'welcome_bonus_wallet' => 'integer',
        'birthday_bonus_enabled' => 'boolean',
        'birthday_bonus_points' => 'integer',
        'birthday_bonus_wallet' => 'integer',
        'manual_adjustments_enabled' => 'boolean',
        'allow_negative_wallet' => 'boolean',
        'show_wallet_to_customer' => 'boolean',
        'show_points_to_customer' => 'boolean',
        'show_tier_to_customer' => 'boolean',
        'nutrition_rewards_enabled' => 'boolean',
        'nutrition_daily_food_log_enabled' => 'boolean',
        'nutrition_daily_food_log_points' => 'integer',
        'nutrition_per_meal_log_enabled' => 'boolean',
        'nutrition_per_meal_log_points' => 'integer',
        'nutrition_daily_water_log_enabled' => 'boolean',
        'nutrition_daily_water_log_points' => 'integer',
        'nutrition_weight_loss_reward_enabled' => 'boolean',
        'nutrition_weight_loss_reward_points' => 'integer',
        'nutrition_online_diet_request_reward_enabled' => 'boolean',
        'nutrition_online_diet_request_reward_points' => 'integer',
        'metadata' => 'array',
    ];
}
